# Generated by Django 3.0.3 on 2020-05-30 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.AddField(
            model_name='order',
            name='items',
            field=models.ManyToManyField(to='shop.OrderItem'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Phones & Tablets', 'Phones & Tablets'), ('Electronics', 'Electronics'), ('Fashion', 'Fashion'), ('Computing', 'Computing'), ('Gaming', 'Gaming'), ('Home & Offices', 'Home & Offices'), ('Health & Beauty', 'Health & Beauty'), ('Supermarket', 'Supermarket'), ('Stay Safe', 'Stay Safe'), ('Library', 'Library'), ('Others', 'Others')], max_length=100, null=True),
        ),
    ]
