# Generated by Django 3.0.3 on 2020-05-30 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20200530_0057'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='discount',
        ),
        migrations.AddField(
            model_name='product',
            name='discount',
            field=models.FloatField(null=True),
        ),
    ]
